import React from "react";
import Image from "next/image";
import Head from "next/head";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";

export const getStaticProps = async () => {
  const response = await fetch("https://fakestoreapi.com/products");
  const data = await response.json();
  return {
    props: { productData: data },
  };
};

const About = (props) => {
  console.log("props", props);
  const { productData } = props;
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <h2>This is About Page</h2>

        <div className="row">
          {productData.map((item) => (
            <div className="col-md-4 mt-3 mb-3">
              <div className="card h-100 text-center">
                <Image
                  className="m-auto"
                  src={item.image}
                  alt="Product image"
                  width={200}
                  height={200}
                />
                <div className="card-body">
                  <h5 className="card-title">{item.title}</h5>
                  <p className="card-text">{item.description}</p>
                </div>
                <div class="card-footer">
                  <strong>Price:&nbsp;</strong>
                  {item.price}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default About;
