import React from "react";
import Image from "next/image";
import Head from "next/head";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import styles from "../styles/About.module.scss";


const About = () => {
 
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <h2 className={styles.about}>This is About Page</h2>
      </div>
    </>
  );
};

export default About;
